Repository szTheory/exifcleaner, pull requests merged in 2020-10, with the labels that each got.

#95 Hotfix - update_exiftool.pl Linux compatibility
  .gitignore
  .resources/nix/bin/.keep
  .resources/win/bin/.keep
  update_exiftool.pl
Labels: devops, linux

#96 Simplify resource path logic between dev and prod
  package.json
  src/common/binaries.ts
  src/common/i18n.ts
  src/common/resources.ts
  src/main/i18n.ts
Labels: devops

#98 Linux app icon fix for .deb and AppImage
  src/common/resources.ts
Labels: bug, linux

#97 pt-BR translation
  .resources/strings.json
Labels: translation

#99 .deb app icon fix
  package.json
Labels: linux
