Repository szTheory/exifcleaner, pull requests merged in 2020-07, with the labels that each got.

#62 Windows UTF-8 filename bug - Second attempt
  src/renderer/add_files.ts
Labels: bug, windows

#67 Feature - ExifTool process management
  src/common/exif_tool_processes.ts
  src/main/dock.ts
  src/renderer/add_files.ts
  src/renderer/display_exif.ts
  src/renderer/exif_get.ts
  src/renderer/exif_remove.ts
  src/renderer/new_process.ts
  src/renderer/select_files.ts
  src/renderer/table_add_row.ts
  src/renderer/table_update_row.ts
  src/types/node-exiftool/index.d.ts
Labels: enhancement

#68 Feature - Add progress bar
  README.md
  src/main/dock.ts
  src/main/init.ts
  src/renderer/select_files.ts
Labels: enhancement

#69 Feature - i18n Translation
  .resources/strings.json
  src/common/binaries.ts
  src/common/env.ts
  src/common/exif_tool_processes.ts
  src/common/i18n.ts
  src/common/resources.ts
  src/main/context_menu.ts
  src/main/i18n.ts
  src/main/index.ts
  src/main/init.ts
  src/main/menu.ts
  src/main/menu_app.ts
  src/main/menu_app_about.ts
  src/main/menu_default.ts
  src/main/menu_edit.ts
  src/main/menu_file.ts
  src/main/menu_file_open.ts
  src/main/menu_help.ts
  src/main/menu_mac.ts
  src/main/menu_view.ts
  src/main/menu_window.ts
  src/main/window_setup.ts
  src/renderer/i18n.ts
  src/renderer/index.html
  src/renderer/index.ts
Labels: enhancement

#73 Update strings.json (add Polish translation).
  .resources/strings.json
Labels: translation

#71 Feature - on Windows, flash frame when files are finished processing
  src/main/dock.ts
  src/main/window_setup.ts
Labels: enhancement, windows
