Repository szTheory/exifcleaner, pull requests merged in 2021-05, with the labels that each got.

#145 docs: Added an Arch Linux note
  README.md
Labels: linux

#147 Polish translation of usertasks. Update of strings.json.
  .resources/strings.json
Labels: translation

#148 Fix XSS and Electron remote shell vulnerabilities by sanitizing HTML output
  CHANGELOG.md
  README.md
  src/renderer/sanitize.ts
  src/renderer/table_update_row.ts
Labels: bug
